### ISSUE TITLE
Fix Horizontal Labels under Mineral Graph

### ISSUE THREAD

**Issue by anthonyjromann** [cis3296s23/MacroCalc704#6]
When adding multiple ingredients, it appears that the mineral graph seems to have horizontal labels overlapping each other and affecting the readability.
<img width="658" alt="Screen Shot 2023-04-18 at 2 27 26 PM" src="https://user-images.githubusercontent.com/76930172/232869882-1418f0db-7b86-4da2-aa62-46850e96bb15.png">

**Comment by jutobash** [comment]
adding rotation to x axis labels on mineral plot

**Comment by jutobash** [comment]
![image](https://user-images.githubusercontent.com/89528532/233467124-8870cf38-6e46-42ba-bfb8-357970a6c095.png)
